### ISSUE TITLE
Are you wondering where to start coding?

### ISSUE THREAD

**Issue by gtainfotech** [gtainfotech/goforit_web#1]
I always find existing apps with translation and without both problematic. The ones with translation force translation based on geolocation and even that's always a problem for traveling professionals, or new immigrants.

Google translate offers a nice starting point, but I really believe that all languages should be covered. Instead of geolocation we should ask users to set language every time they visit with a remember my choice checkbox (preferably with no cookie) and the possibility of changing their UI language from any page of the webapp.

But as I mentioned above we shouldn't suffice it to translations provided by Google. So we will follow in the footsteps of some of the existing webapps for crowd translation. This, on the back end will be: for all nonEnglish languages including those with Google translations, there should be a way to offer a better translation, without incurring any bandwidth or any other fees, in addition, there should be, a reward program in place for the best chosen translations only by public votes (only for members [basic & professional] who have provided email addresses on their account details page) and this per translation reward amount should be adjustable from the admin panel. For more on this refer to page 22 of the definition updated word document.

**Comment by gtainfotech** [comment]
But if a translation is deleted by admins, should there be a deletion notification? What do you think guys?

**Comment by gtainfotech** [comment]
Can we offer translation reward to guests (nonmember users)? Do we need cookies enabled for this?

**Comment by gtainfotech** [comment]
When I'm abroad and am not familiar with the local alphabet, the problem sometimes presents itself. But I guess geolocation works fine for the majority of the visitors. Though it would be nice to have a link titled "English" or "Language" in English. Any solution for this?

**Comment by gtainfotech** [comment]
When I am in those countries, I just can't locate the "Language" link in the local language, after geolocation determined that I speak Mandarin, for example. But my solution could be an overkill. I would appreciate any opinions.

**Comment by prolay7** [comment]
Is anyone started working on the project?

**Comment by gtainfotech** [comment]
@prolay7, no, nobody has done anything yet. A pull request for the translation module would be nice.

**Comment by lFighterl** [comment]
@gtainfotech, how about if we not use geolocation and give user a list of languages to pick, so they can choose from whichever they can understand.

**Comment by gtainfotech** [comment]
@lFighterl, yeah, that was my idea, too. But then what language should the initial link or dropdown menu title be in? I guess the same problem can occur for more (local) people in this way if it is in English. At second glance geolocation seems like a good idea, but the language selection link's title is better in English.

**Comment by lFighterl** [comment]
My suggestion would be, we can keep English as the default language, nd then the option to change the language can be easily accessible right from the main UI, so it it very obvious even for the user that don't understand english. Like we can have a dropdown at the front page that say EN-US or something like that, it will make it obvious that you can change language from that, or we can make an animated splash page, while loading the app, that will give option to choose language, and because we are dedicating a full screen to it, we can have it in multiple languages, english can be the default one and then other one can the geological one. if i am not very clear let me know, i'll make an illutration of it.

**Comment by gtainfotech** [comment]
@lFighterl, yeah that's clear. The full page option is great. But in case one's preferred language is not English or the local language, it's okay to select it once, but it is a hassle to do it every time so the preferred lang should be saved on the server for members and upon login be the display (and content) language as much as feasible. Yeah, a lot of local people would like to interact with English language content as much as possible, so they can practice the language, but when the option to select it is buried under a ton of different things, makes it very difficult. A flag image in conjunction with the language name is a good idea, too.

**Comment by gtainfotech** [comment]
The objective is to get the desired language in front of as many people as possible as quickly as possible so it's OK to have a greater portion of the landing page devoted to language selection but the default language should be selected by geolocation. Seems like Google and Facebook have done their homework. But then the language selection screen should be mainly in English.

**Comment by gtainfotech** [comment]
So I guess geolocation assisted default language selection is okay, provided that the language re-selection bar is displayed prominently in English. If there is no further comment @lFighterl can have the final say.

**Comment by lFighterl** [comment]
Yeah, that sounds good to me.
